name = "abid-khan-institute-hub"
main = "worker.js"
compatibility_date = "2026-02-10"

# Bindings for AI (Llama/Mistral)
[ai]
binding = "AI"

# Bindings for your Database (KV Namespace)
[[kv_namespaces]]
binding = "abid_pedagogy_db"
id = "68cf91c6f606eb4c30cc5bf692045694"

[observability]
enabled = true
