name = "abid-khan-institute-hub"
main = "worker.js"
compatibility_date = "2026-02-10"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "abid_pedagogy_db"
id = "68cf91c6f606eb4c30cc5bf692045694"

[vars]
EMAIL_FROM = "verify@abid-pedagogy-hub.com"

[observability]
enabled = true
